#!/usr/bin/env bash
# Generate Rust types from the vendored X API OpenAPI spec.
# Requires: cargo-typify (cargo install cargo-typify), python3
# Run from repo root: ./scripts/generate-types.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SPEC="$REPO_ROOT/openapi/x-api-openapi.json"
OUTPUT="$REPO_ROOT/src/types/generated.rs"

if [ ! -f "$SPEC" ]; then
  echo "Error: OpenAPI spec not found at $SPEC" >&2
  echo "Run scripts/download-openapi.sh first." >&2
  exit 1
fi

if ! cargo typify --help &> /dev/null; then
  echo "Error: cargo-typify not installed. Run: cargo install cargo-typify" >&2
  exit 1
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Step 1: Extract selective schemas with transitive dependencies, patch out
# date-time format and regex patterns (we parse timestamps and validate patterns
# ourselves; these would pull in chrono and regress as runtime dependencies).
python3 - "$SPEC" "$TMPDIR/schemas.json" << 'PYTHON'
import json, sys

with open(sys.argv[1]) as f:
    spec = json.load(f)

all_schemas = spec["components"]["schemas"]

# Core schemas bird needs (entity types + response wrappers)
ROOT_SCHEMAS = [
    "Tweet", "User", "Media", "Place", "Poll", "Expansions", "Error",
    "Get2TweetsSearchRecentResponse", "Get2TweetsIdResponse",
    "Get2TweetsResponse", "Get2UsersIdBookmarksResponse",
    "Get2UsersByUsernameUsernameResponse", "Get2UsersMeResponse",
]

def resolve_refs(obj, refs=None):
    if refs is None: refs = set()
    if isinstance(obj, dict):
        if "$ref" in obj:
            for pfx in ("#/components/schemas/", "#/definitions/"):
                if obj["$ref"].startswith(pfx):
                    refs.add(obj["$ref"][len(pfx):])
        for v in obj.values(): resolve_refs(v, refs)
    elif isinstance(obj, list):
        for item in obj: resolve_refs(item, refs)
    return refs

# Collect transitive closure
collected, queue, seen = {}, list(ROOT_SCHEMAS), set()
while queue:
    name = queue.pop(0)
    if name in seen: continue
    seen.add(name)
    if name not in all_schemas:
        print(f"  WARNING: schema '{name}' not found", file=sys.stderr)
        continue
    collected[name] = all_schemas[name]
    for ref in resolve_refs(all_schemas[name]):
        if ref not in seen: queue.append(ref)

# Patch: remove date-time format and regex patterns
def patch(obj):
    if isinstance(obj, dict):
        if obj.get("format") == "date-time": del obj["format"]
        if "pattern" in obj and isinstance(obj["pattern"], str): del obj["pattern"]
        for v in obj.values(): patch(v)
    elif isinstance(obj, list):
        for item in obj: patch(item)

# Rewrite refs from OpenAPI to JSON Schema style
def rewrite_refs(obj):
    if isinstance(obj, dict):
        if "$ref" in obj:
            obj["$ref"] = obj["$ref"].replace("#/components/schemas/", "#/definitions/")
        for v in obj.values(): rewrite_refs(v)
    elif isinstance(obj, list):
        for item in obj: rewrite_refs(item)

for s in collected.values():
    patch(s)
    rewrite_refs(s)

out = {"$schema": "http://json-schema.org/draft-07/schema#", "definitions": collected}
with open(sys.argv[2], "w") as f:
    json.dump(out, f, indent=2)
print(f"Extracted {len(collected)} schemas ({len(ROOT_SCHEMAS)} roots)", file=sys.stderr)
PYTHON

# Step 2: Run cargo-typify
cargo typify "$TMPDIR/schemas.json" -o "$TMPDIR/types.rs"

# Step 3: Prepend @generated header
{
  echo '// @generated by cargo-typify from openapi/x-api-openapi.json — DO NOT EDIT'
  echo '// Selective generation: 60 schemas from X API v2 spec (patched: no date-time format, no regex patterns)'
  echo '// Regenerate: ./scripts/generate-types.sh'
  echo ''
  cat "$TMPDIR/types.rs"
} > "$OUTPUT"

echo "Generated $OUTPUT ($(wc -l < "$OUTPUT") lines)"
