name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE-*'
      - 'docs/**'
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    uses: brettdavies/.github/.github/workflows/rust-ci.yml@main
