name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

permissions:
  contents: write
  id-token: write

jobs:
  pipeline:
    uses: brettdavies/.github/.github/workflows/rust-release.yml@469eb204a6d9e88af0f1e2d27c40b45136810344 # main as of 2026-05-30
    with:
      crate: bird
      bin: bird
    secrets:
      CI_RELEASE_TOKEN: ${{ secrets.CI_RELEASE_TOKEN }}
